USE security_test;
DELETE FROM questions WHERE true;
DELETE FROM answers WHERE true;
INSERT INTO questions(question_id, text, type) VALUES(1, 'What is the most dangerous type of corrupted soft?', 'RADIO');
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (0, 'Trojan', true, 1);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (1, 'Worm', false, 1);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (2, 'Spy soft', false, 1);
INSERT INTO questions(question_id, text, type) VALUES(2, 'What is the most common authentication type?', 'RADIO');
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (3, 'Static password', true, 2);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (4, 'Dynamic password', false, 2);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (5, 'PKI systems', false, 2);
INSERT INTO questions(question_id, text, type) VALUES(3, 'Under which systems are viruses most dynamically distributed?', 'RADIO');
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (6, 'Windows', false, 3);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (7, 'Android', true, 3);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (8, 'MacOS', false, 3);
INSERT INTO questions(question_id, text, type) VALUES(4, 'What is the final step in building a security system?', 'RADIO');
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (9, 'Planing', false, 4);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (10, 'Testing', false, 4);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (11, 'Supporting', true, 4);
INSERT INTO questions(question_id, text, type) VALUES(5, 'What information security threats are deliberate?', 'RADIO');
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (12, 'Stuff mistakes', false, 5);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (13, 'Unauthenticated access', true, 5);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (14, 'Opening e-mail with attached malware', false, 5);
INSERT INTO questions(question_id, text, type) VALUES(6, 'What is the security approach?', 'RADIO');
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (15, 'Complex', true, 6);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (16, 'Theoretical', false, 6);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (17, 'Practical', false, 6);
INSERT INTO questions(question_id, text, type) VALUES(7, 'The cryptographic information protection system is:', 'RADIO');
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (18, 'Crypto Pro', false, 7);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (19, 'BFox Pro', true, 7);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (20, 'CAudit Pro', false, 7);
INSERT INTO questions(question_id, text, type) VALUES(8, 'What viruses are activated at the very beginning of work with the operating system?', 'RADIO');
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (21, 'Trojan', false, 8);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (22, 'Loader viruses', true, 8);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (23, 'Worms', false, 8);
INSERT INTO questions(question_id, text, type) VALUES(9, 'Stuxnet is:', 'RADIO');
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (24, 'Industrial virus', true, 9);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (25, 'Trojan software', false, 9);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (26, 'Macro virus', false, 9);
INSERT INTO questions(question_id, text, type) VALUES(10, 'Targeted Attack is:', 'RADIO');
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (27, 'Attack on a specific user''s computer', false, 10);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (28, 'Attack on a computer system of a large enterprise', true, 10);
INSERT INTO answers(answer_id, text, is_right, question_id) VALUES (29, 'Attack on network equipment', false, 10);
